[development]
secret_key = "jXIozNBJofF9SoXQk1t+0VOO0h3Ex7/4Zx3naWLk+Gs="

[staging]
address = "0.0.0.0"
port = 80
log = "normal"
secret_key = "jXIozNBJofF9SoXQk1t+0VOO0h3Ex7/4Zx3naWLk+Gs="

[production]
address = "0.0.0.0"
port = 80
log = "critical"
secret_key = "jXIozNBJofF9SoXQk1t+0VOO0h3Ex7/4Zx3naWLk+Gs="
